# Generated by Django 3.0.2 on 2020-01-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='isInvasive',
            field=models.BooleanField(default=False),
        ),
    ]
