# Generated by Django 3.0.2 on 2020-01-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0002_userplant_isinvasive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='isInvasive',
            field=models.CharField(max_length=20),
        ),
    ]
