# Generated by Django 3.0.2 on 2020-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0003_auto_20200124_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
