# Generated by Django 3.0.2 on 2020-01-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0004_auto_20200125_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='scientificNameAuthor',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
