# Generated by Django 3.0.2 on 2020-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0005_auto_20200125_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='family',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='isInvasive',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='nationalCommonName',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='nativeState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='synonymSymbol',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
