# Generated by Django 3.0.2 on 2020-02-07 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardsApp', '0007_auto_20200125_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='numberOfPlant',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
